feeds:
  - name: 'AVAX/USD'
    feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
  - name: 'ETH/USD'
    feedId: '0x000359843a543ee2fe414dc14c7e7920ef10f4372990b79d6361cdc0dd1ba782'
chainId: 43113
gasCap: '150000'
interval: '*/30 * * * * *'
priceDeltaPercentage: 0.01
chains:
  - id: 995
    name: '🔥 5ireChain'
    currencyName: '5ire Token'
    currencySymbol: '5IRE'
    currencyDecimals: 18
    rpc: 'https://rpc.5ire.network'
  - id: 84532
    name: 'Base Sepolia Custom'
    currencyName: 'Sepolia Ether'
    currencySymbol: 'ETH'
    currencyDecimals: 18
    rpc: 'https://sepolia.base.org'
    testnet: true
verifierAddresses:
  - chainId: 995
    address: '0x...'
  - chainId: 84532
    address: '0x...'
targetChains:
  - chainId: 43113
    targetContracts:
      - feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
        address: '0xfa162F0A25b2C2aA32Ddaacda872B6D7b2c38E47'
        functionName: 'set'
        functionArgs:
          - 'feedId'
          - 'validFromTimestamp'
          - 'observationsTimestamp'
          - 'nativeFee'
          - 'linkFee'
          - 'expiresAt'
          - 'price'
          - 'bid'
          - 'ask'
        abi:
          [
            {
              'inputs':
                [
                  {
                    'internalType': 'bytes32',
                    'name': 'feedId',
                    'type': 'bytes32',
                  },
                  {
                    'internalType': 'uint32',
                    'name': 'validFromTimestamp',
                    'type': 'uint32',
                  },
                  {
                    'internalType': 'uint32',
                    'name': 'observationsTimestamp',
                    'type': 'uint32',
                  },
                  {
                    'internalType': 'uint192',
                    'name': 'nativeFee',
                    'type': 'uint192',
                  },
                  {
                    'internalType': 'uint192',
                    'name': 'linkFee',
                    'type': 'uint192',
                  },
                  {
                    'internalType': 'uint32',
                    'name': 'expiresAt',
                    'type': 'uint32',
                  },
                  {
                    'internalType': 'int192',
                    'name': 'price',
                    'type': 'int192',
                  },
                  { 'internalType': 'int192', 'name': 'bid', 'type': 'int192' },
                  { 'internalType': 'int192', 'name': 'ask', 'type': 'int192' },
                ],
              'name': 'set',
              'outputs': [],
              'stateMutability': 'nonpayable',
              'type': 'function',
            },
          ]
vm: 'evm'
svm:
  cluster: 'devnet'
  chains:
    - cluster: 'devnet'
      name: 'Solana Devnet'
      rpc: 'https://api.devnet.solana.com'
      testnet: true
  targetChains:
    - cluster: 'devnet'
      targetPrograms:
        - feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
          instructionName: 'updatePrice'
          instructionArgs:
            - name: 'feedId'
              type: 'string'
            - name: 'price'
              type: 'number'
            - name: 'validFromTimestamp'
              type: 'number'
          instructionPDAs:
            - 'price-feed'
          idl:
            {
              'address': 'zDecnPdGtuXypFqhnUsVJtUT5BCwgdzygyECT1bKGNo',
              'metadata':
                {
                  'name': 'price_feed',
                  'version': '0.1.0',
                  'spec': '0.1.0',
                  'description': 'Created with Anchor',
                },
              'instructions':
                [
                  {
                    'name': 'initialize',
                    'discriminator': [175, 175, 109, 31, 13, 152, 155, 237],
                    'accounts':
                      [
                        {
                          'name': 'price_feed',
                          'writable': true,
                          'pda':
                            {
                              'seeds':
                                [
                                  {
                                    'kind': 'const',
                                    'value':
                                      [
                                        112,
                                        114,
                                        105,
                                        99,
                                        101,
                                        45,
                                        102,
                                        101,
                                        101,
                                        100,
                                      ],
                                  },
                                ],
                            },
                        },
                        { 'name': 'signer', 'writable': true, 'signer': true },
                        {
                          'name': 'system_program',
                          'address': '11111111111111111111111111111111',
                        },
                      ],
                    'args': [],
                  },
                  {
                    'name': 'update_price',
                    'discriminator': [61, 34, 117, 155, 75, 34, 123, 208],
                    'accounts':
                      [
                        { 'name': 'price_feed', 'writable': true },
                        { 'name': 'signer', 'signer': true },
                      ],
                    'args':
                      [
                        { 'name': 'feed_id', 'type': 'string' },
                        { 'name': 'price', 'type': 'i128' },
                        { 'name': 'date', 'type': 'i128' },
                      ],
                  },
                ],
              'accounts':
                [
                  {
                    'name': 'PriceFeed',
                    'discriminator': [189, 103, 252, 23, 152, 35, 243, 156],
                  },
                ],
              'types':
                [
                  {
                    'name': 'PriceFeed',
                    'type':
                      {
                        'kind': 'struct',
                        'fields':
                          [
                            { 'name': 'feed_id', 'type': 'string' },
                            { 'name': 'price', 'type': 'i128' },
                            { 'name': 'date', 'type': 'i128' },
                          ],
                      },
                  },
                ],
            }
