services:
  transmitter:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=transmitter-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_KEY_EVM=${PRIVATE_KEY_EVM}
      - SECRET_KEY_SVM=${SECRET_KEY_SVM}
      - DATASTREAMS_HOSTNAME=${DATASTREAMS_HOSTNAME}
      - DATASTREAMS_WS_HOSTNAME=${DATASTREAMS_WS_HOSTNAME}
      - DATASTREAMS_CLIENT_ID=${DATASTREAMS_CLIENT_ID}
      - DATASTREAMS_CLIENT_SECRET=${DATASTREAMS_CLIENT_SECRET}
    volumes:
      - ./logs:/transmitter/logs
  transmitter-redis:
    image: redis:latest
    command: redis-server --save 60 1 --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
networks:
  default:
    driver: bridge
