services:
  transmitter:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=transmitter-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DATASTREAMS_HOSTNAME=${DATASTREAMS_HOSTNAME}
      - DATASTREAMS_WS_HOSTNAME=${DATASTREAMS_WS_HOSTNAME}
      - DATASTREAMS_CLIENT_ID=${DATASTREAMS_CLIENT_ID}
      - DATASTREAMS_CLIENT_SECRET=${DATASTREAMS_CLIENT_SECRET}
      - DATASTREAMS_WS_RECONNECT_ENABLED=${DATASTREAMS_WS_RECONNECT_ENABLED:-true}
      - DATASTREAMS_WS_RECONNECT_MAX_ATTEMPTS=${DATASTREAMS_WS_RECONNECT_MAX_ATTEMPTS:-10000}
      - DATASTREAMS_WS_RECONNECT_INTERVAL=${DATASTREAMS_WS_RECONNECT_INTERVAL:-5000}
      - DATASTREAMS_WS_RECONNECT_STALE_INTERVAL=${DATASTREAMS_WS_RECONNECT_STALE_INTERVAL:-60000}
      - HEALTH_PORT=${HEALTH_PORT:-8081}
    volumes:
      - ./logs:/transmitter/logs
  transmitter-redis:
    image: redis:latest
    command: redis-server --save 60 1 --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
networks:
  default:
    driver: bridge
